name: 'Rename PR'

on:
  pull_request:
    types: [unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    uses: actions/github-script@v4
    with:
      script: console.log(context)
