name: 'Label Actions'

on:
  pull_request:
    types: [unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
