name: 'Rename PR'
on:
  pull_request:

  issues:
    
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const commits_url = context.payload.pull_request.commits_url
            const result = await github.request(commits_url)
            console.log(result.data[result.data.length - 1])
            console.log(context.payload.pull_request)

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
