name: 'Rename PR'
on:
  pull_request:

  issues:
    
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            //const diff_url = context.payload.pull_request.diff_url
            //const result = await github.request(diff_url)
            console.log(context)

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
